Repository zapier/babel-preset-zapier, pull requests merged in 2018-11, with the labels that each got.

#6 allow tests in *.test.js
  __snapshots__/index.js.snap
  __snapshots__/index.test.js.snap
  index.test.js
  package.json
Labels: enhancement

#7 Add emotion plugin
  index.js
  package.json
  yarn.lock
Labels: enhancement, needs-review

#10 Fix issues with transpiled code in Edge
  __snapshots__/index.js.snap
  __snapshots__/index.test.js.snap
  index.js
  index.test.js
  package.json
  yarn.lock
Labels: bug, needs-review
